added printing of usage/help

diff --git a/idle-spindown/scripts/idle-spindown b/idle-spindown/scripts/idle-spindown
--- a/idle-spindown/scripts/idle-spindown
+++ b/idle-spindown/scripts/idle-spindown
@@ -13,15 +13,25 @@
 # - check for root
 # - also support uuids to identify sdX
 
-# check argument
-if [ ! $1 ]; then
-echo "You have to provide a device or uuid!" 1>&2
-exit 1
-fi
 
 # check permissions (root)
 if [ "$(id -u)" != "0" ]; then
-echo “This script must be run as root” 1>&2
+echo "This script must be run as root" 1>&2
+exit 1
+fi
+
+# check argument
+if [ ! $1 ]; then
+echo "Usage: idle-spindown DEVICE-PATTERN" 1>&2
+echo "Spins down a idle drive." 1>&2
+echo "" 1>&2
+echo "	DEVICE-PATTERN	unique part of /dev/sdX, /dev/hdX or UUID" 1>&2
+echo "			if more than one device matches one is choosen" 1>&2
+echo "" 1>&2
+echo "Example usage:" 1>&2
+echo "idle-spindown sdb # device path part" 1>&2
+echo "idle-spindown 44ef7a58-25a7 # uuid part" 1>&2
+echo "Please provide DEVICE-PATTERN"
 exit 1
 fi
 
@@ -29,8 +39,8 @@ fi
 disk=$(/sbin/blkid | grep -m 1 $1 | cut -c 6-8)
 
 #check if the disk uuid (or sdX), or pieces of it were ok
-if [ ! -n $disk ]; then
-echo “no such disk – disk!” 1>&2
+if [ ! $disk ]; then
+echo "Couldn't find device! Please check your DEVICE-PATTERN." 1>&2
 exit 1
 fi
 
